# .github/workflows/python-app.yml
name: Python application test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"] # Test on multiple Python versions

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest # Add other linters/tools if used
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Lint with flake8 # Optional: Add linting step
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      env: # Set dummy env var for tests if needed, secrets shouldn't be used here
         GOOGLE_API_KEY: "DUMMY_KEY_FOR_TESTING" # Ensure tests mock the API call
      run: |
        pytest